[package]
name = "niri-focused-booster"
version = "0.3.0"
edition = "2024"

[dependencies]
ctrlc = { version = "3.5.2", features = ["termination"] }
niri-ipc = "=26.4.0"
xcb = { version = "1.7.0", features = ["res"] }
zbus = "5.14.0"

[patch.crates-io]
niri-ipc = { path = "./niri/niri-ipc" }

[profile.release]
lto = "thin"
